# Generated by Django 3.1.4 on 2021-04-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('post_code', models.IntegerField(primary_key=True, serialize=False)),
                ('contCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(default=-1)),
                ('lng', models.FloatField(default=-1)),
                ('capacity', models.IntegerField(default='1')),
                ('request_count', models.IntegerField(default='0')),
                ('QRcode', models.CharField(blank=True, default='', max_length=45)),
                ('post_code', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='container.postcode')),
            ],
        ),
    ]
