# Generated by Django 3.1.4 on 2021-04-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
        ('command_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.TimeField()),
                ('login_date', models.DateField()),
                ('logout_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCommandCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.TimeField()),
                ('login_date', models.DateField()),
                ('logout_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.commandcenter')),
            ],
        ),
    ]
