# Generated by Django 3.1.4 on 2021-04-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_id', models.CharField(default='', max_length=128)),
                ('plate_num', models.TextField()),
                ('miles', models.FloatField()),
                ('veh_type', models.TextField()),
                ('odometer', models.FloatField(blank=True, default=None, null=True)),
                ('veh_model', models.CharField(default='', max_length=45)),
                ('enrol_date', models.DateField(default='2007/1/1')),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map_Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.IntegerField(blank=True, default=None, null=True)),
                ('isTaskFinished', models.BooleanField(default=False)),
                ('post_code', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='container.postcode')),
                ('veh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
