# Generated by Django 3.1.4 on 2021-04-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=128)),
                ('password', models.CharField(max_length=45)),
                ('role', models.CharField(blank=True, max_length=45)),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(blank=True, max_length=45)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(default='', max_length=45)),
                ('full_name', models.CharField(default='', max_length=128)),
                ('enrol_date', models.DateField()),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date_begin', models.DateTimeField(auto_now_add=True)),
                ('assignment_date_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('isTaskFinished', models.BooleanField(default=False)),
                ('veh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
    ]
