# Generated by Django 3.1.4 on 2021-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(blank=True, default='', max_length=45)),
                ('full_name', models.CharField(default='', max_length=128)),
                ('gender', models.CharField(default='', max_length=128)),
                ('country', models.CharField(default='', max_length=45)),
                ('date_of_birth', models.DateField()),
                ('enrol_date', models.DateField()),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
