# Generated by Django 3.1.4 on 2021-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('national_number', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('points', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(blank=True, max_length=45)),
            ],
        ),
    ]
